### ISSUE TITLE
NPM Install - No Compatible Versions Found

### ISSUE THREAD

**Issue by cpollard0** [cloudsploit/scans#27]
When doing an NPM install I get an error "No compatible version found: async@^2.0.0". 

Any help? 

Thanks!

**Comment by davidpelayo** [comment]
Probably because if you observe the releases of that package, there isn't still any ^2.0.0 or similar (official) released. The reason, I don't know, but it might be they renamed tags on releases.

<img width="463" alt="screen shot 2016-05-26 at 11 30 17 am" src="https://cloud.githubusercontent.com/assets/84540/15570229/413b5ff2-2335-11e6-9ebe-f7b882194f46.png">

If you set on your forked package.json `async@2.0.0-rc.5`, it should work.

**Comment by cpollard0** [comment]
That did it, thanks David!
